import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/providers";
import { AuthProvider } from "@/context/AuthContext";
import NavBar from "@/components/common/NavBar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  dark text-foreground bg-[#10131e]`}
      >
        <Providers>
          <AuthProvider>
            <NavBar />
            {children}
            <Toaster richColors theme="dark" />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
